import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

export const DEFAULT_MC_VERSION = '1.20.4';

/**
 * Downloads candidate URLs for Minecraft 1.20.4:
 * 1. Paper Fill v3 direct object (Paper build 499)
 * 2. Paper legacy v2 endpoint (fallback)
 * 3. Official Mojang Vanilla 1.20.4 server jar (fallback)
 */
export const PAPER_1_20_4_FILL_URL =
  'https://fill-data.papermc.io/v1/objects/cabed3ae77cf55deba7c7d8722bc9cfd5e991201c211665f9265616d9fe5c77b/paper-1.20.4-499.jar';
export const PAPER_1_20_4_LEGACY_URL =
  'https://api.papermc.io/v2/projects/paper/versions/1.20.4/builds/499/downloads/paper-1.20.4-499.jar';
export const VANILLA_1_20_4_URL =
  'https://piston-data.mojang.com/v1/objects/8dd1a28015f51b1803213892b50b7b4fc76e594d/server.jar';

export const SERVER_PROPERTIES_CONTENT = `# Aldeano Build MCP Local Dev Server Configuration
# ==============================================================================
# SECURITY NOTICE:
# This server is configured exclusively for isolated local testing.
# It strictly binds to 127.0.0.1 (localhost) and disables online-mode so local
# LLM bots (Mineflayer) can connect without Mojang/Microsoft account credentials.
# NEVER bind this configuration to 0.0.0.0 or expose port 25565 to the internet.
# ==============================================================================
server-ip=127.0.0.1
server-port=25565
online-mode=false
gamemode=creative
difficulty=peaceful
spawn-protection=0
allow-flight=true
view-distance=8
simulation-distance=6
max-players=20
white-list=false
enable-rcon=false
motd=Aldeano Build MCP Dev Server
`;

export const EULA_CONTENT = `# By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).
# Generated by Aldeano Build MCP setup script
eula=true
`;

export interface JavaCheckResult {
  installed: boolean;
  version?: string;
  majorVersion?: number;
  output?: string;
  error?: string;
}

/**
 * Checks if Java is installed and returns version details.
 */
export function checkJavaInstalled(): JavaCheckResult {
  try {
    const result = spawnSync('java', ['-version'], {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe']
    });

    if (result.error) {
      return {
        installed: false,
        error: result.error.message || 'Java executable not found in PATH'
      };
    }

    const output = `${result.stdout || ''}\n${result.stderr || ''}`.trim();
    if (!output) {
      return {
        installed: false,
        error: 'No output from java -version'
      };
    }

    return parseJavaVersionOutput(output);
  } catch (err: unknown) {
    return {
      installed: false,
      error: (err as Error).message || 'Failed to check Java'
    };
  }
}

/**
 * Parses java -version command output.
 */
export function parseJavaVersionOutput(output: string): JavaCheckResult {
  const versionMatch = output.match(/(?:openjdk|java)\s+version\s+"?([0-9._]+)"?/i);
  if (!versionMatch) {
    return {
      installed: true,
      output: output.trim()
    };
  }

  const version = versionMatch[1];
  let majorVersion = 0;
  if (version.startsWith('1.')) {
    majorVersion = parseInt(version.split('.')[1], 10);
  } else {
    majorVersion = parseInt(version.split('.')[0], 10);
  }

  return {
    installed: true,
    version,
    majorVersion,
    output: output.trim()
  };
}

/**
 * Resolves the default local Minecraft directory (.dev/minecraft).
 */
export function getMinecraftDevDir(baseDir: string = process.cwd()): string {
  return path.resolve(baseDir, '.dev', 'minecraft');
}

/**
 * Ensures required directories exist.
 */
export function ensureMinecraftDir(mcDir: string): void {
  if (!fs.existsSync(mcDir)) {
    fs.mkdirSync(mcDir, { recursive: true });
    console.log(`[setup] Created directory: ${mcDir}`);
  }
}

/**
 * Writes eula.txt with eula=true.
 */
export function writeEula(mcDir: string): void {
  const eulaPath = path.join(mcDir, 'eula.txt');
  fs.writeFileSync(eulaPath, EULA_CONTENT, 'utf-8');
  console.log(`[setup] Wrote EULA acceptance to ${eulaPath}`);
}

/**
 * Generates local development server.properties.
 */
export function writeServerProperties(mcDir: string): void {
  const propsPath = path.join(mcDir, 'server.properties');
  fs.writeFileSync(propsPath, SERVER_PROPERTIES_CONTENT, 'utf-8');
  console.log(`[setup] Generated server.properties (127.0.0.1:25565, creative, peaceful) at ${propsPath}`);
}

/**
 * Streams download with progress indication.
 */
export async function downloadFileWithProgress(url: string, destPath: string, label: string): Promise<void> {
  const tempPath = `${destPath}.tmp-${Date.now()}`;
  console.log(`[setup] Connecting to download ${label}...`);
  console.log(`[setup] URL: ${url}`);

  const response = await fetch(url, {
    headers: {
      'User-Agent': 'AldeanoBuildMCP/2.0 (setup-server; https://github.com/Aldeano-Build-MCP)'
    }
  });

  if (!response.ok || !response.body) {
    throw new Error(`HTTP ${response.status} ${response.statusText} from ${url}`);
  }

  const contentLengthHeader = response.headers.get('content-length');
  const totalBytes = contentLengthHeader ? parseInt(contentLengthHeader, 10) : 0;
  const totalMbStr = totalBytes > 0 ? (totalBytes / (1024 * 1024)).toFixed(1) : 'unknown';

  console.log(`[setup] Size: ${totalMbStr} MB. Downloading...`);

  let downloadedBytes = 0;
  let lastReportedPercent = -1;

  const fileStream = fs.createWriteStream(tempPath);
  const reader = response.body.getReader();

  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      if (value) {
        fileStream.write(Buffer.from(value));
        downloadedBytes += value.length;

        if (totalBytes > 0) {
          const percent = Math.floor((downloadedBytes / totalBytes) * 100);
          if (percent !== lastReportedPercent && (percent % 10 === 0 || percent === 100)) {
            lastReportedPercent = percent;
            const currentMbStr = (downloadedBytes / (1024 * 1024)).toFixed(1);
            const barWidth = 25;
            const filled = Math.round((barWidth * percent) / 100);
            const empty = barWidth - filled;
            const bar = '='.repeat(filled) + '-'.repeat(empty);

            if (process.stdout.isTTY) {
              process.stdout.write(`\r[setup] [${bar}] ${percent}% (${currentMbStr} / ${totalMbStr} MB)`);
            } else {
              console.log(`[setup] Download progress: ${percent}% (${currentMbStr} / ${totalMbStr} MB)`);
            }
          }
        }
      }
    }
  } catch (err) {
    fileStream.close();
    if (fs.existsSync(tempPath)) {
      try {
        fs.unlinkSync(tempPath);
      } catch {
        // ignore cleanup error
      }
    }
    throw err;
  }

  await new Promise<void>((resolve, reject) => {
    fileStream.end(() => resolve());
    fileStream.on('error', reject);
  });

  if (process.stdout.isTTY && totalBytes > 0) {
    process.stdout.write('\n');
  }

  const stats = fs.statSync(tempPath);
  if (totalBytes > 0 && stats.size !== totalBytes) {
    fs.unlinkSync(tempPath);
    throw new Error(`Incomplete download: expected ${totalBytes} bytes but got ${stats.size} bytes`);
  }

  if (fs.existsSync(destPath)) {
    fs.unlinkSync(destPath);
  }
  fs.renameSync(tempPath, destPath);

  const finalMbStr = (stats.size / (1024 * 1024)).toFixed(1);
  console.log(`[setup] Successfully downloaded and verified ${label} (${finalMbStr} MB)`);
}

/**
 * Resolves Paper or Vanilla server jar URL and downloads it into mcDir/server.jar.
 */
export async function downloadServerJar(mcDir: string, version: string = DEFAULT_MC_VERSION, force = false): Promise<string> {
  const destJar = path.join(mcDir, 'server.jar');

  if (!force && fs.existsSync(destJar)) {
    const stats = fs.statSync(destJar);
    if (stats.size > 10 * 1024 * 1024) {
      console.log(`[setup] server.jar already exists at ${destJar} (${(stats.size / (1024 * 1024)).toFixed(1)} MB).`);
      console.log(`[setup] Use --force or delete the file to re-download.`);
      return destJar;
    }
  }

  console.log(`[setup] Preparing server jar for Minecraft version: ${version}...`);

  // Build candidate URL list
  const candidates: { name: string; url: string }[] = [];

  if (version === '1.20.4') {
    candidates.push({ name: 'Paper 1.20.4 (Build 499 - Fill v3)', url: PAPER_1_20_4_FILL_URL });
    candidates.push({ name: 'Paper 1.20.4 (Build 499 - Legacy)', url: PAPER_1_20_4_LEGACY_URL });
    candidates.push({ name: 'Vanilla 1.20.4 (Mojang official)', url: VANILLA_1_20_4_URL });
  } else {
    // Attempt dynamic Paper Fill v3 API lookup
    try {
      console.log(`[setup] Querying PaperMC API for version ${version}...`);
      const apiRes = await fetch(`https://fill.papermc.io/v3/projects/paper/versions/${version}`, {
        headers: { 'User-Agent': 'AldeanoBuildMCP/2.0' }
      });
      if (apiRes.ok) {
        const apiData = (await apiRes.json()) as { builds?: number[] };
        const builds = apiData.builds;
        if (builds && builds.length > 0) {
          const latestBuild = builds[0];
          const buildRes = await fetch(`https://fill.papermc.io/v3/projects/paper/versions/${version}/builds/${latestBuild}`, {
            headers: { 'User-Agent': 'AldeanoBuildMCP/2.0' }
          });
          if (buildRes.ok) {
            const buildData = (await buildRes.json()) as { downloads?: { 'server:default'?: { url?: string } } };
            const downloadUrl = buildData.downloads?.['server:default']?.url;
            if (downloadUrl) {
              candidates.push({ name: `Paper ${version} (Build ${latestBuild})`, url: downloadUrl });
            }
          }
        }
      }
    } catch (e: unknown) {
      console.warn(`[setup] Warning: Failed to query PaperMC API for ${version}: ${(e as Error).message}`);
    }

    // Always fallback to Mojang official version manifest if needed
    try {
      console.log(`[setup] Querying Mojang version manifest for ${version}...`);
      const manifestRes = await fetch('https://launchermeta.mojang.com/mc/game/version_manifest_v2.json');
      if (manifestRes.ok) {
        const manifestData = (await manifestRes.json()) as { versions?: { id: string; url: string }[] };
        const verObj = manifestData.versions?.find((v) => v.id === version);
        if (verObj) {
          const verRes = await fetch(verObj.url);
          if (verRes.ok) {
            const verData = (await verRes.json()) as { downloads?: { server?: { url: string } } };
            const vanillaUrl = verData.downloads?.server?.url;
            if (vanillaUrl) {
              candidates.push({ name: `Vanilla ${version} (Mojang official)`, url: vanillaUrl });
            }
          }
        }
      }
    } catch (e: unknown) {
      console.warn(`[setup] Warning: Failed to query Mojang manifest for ${version}: ${(e as Error).message}`);
    }
  }

  if (candidates.length === 0) {
    throw new Error(`Could not find download candidates for Minecraft version ${version}`);
  }

  let downloaded = false;
  let lastError: Error | null = null;

  for (const candidate of candidates) {
    try {
      console.log(`[setup] Attempting download from: ${candidate.name}...`);
      await downloadFileWithProgress(candidate.url, destJar, candidate.name);
      downloaded = true;
      break;
    } catch (err: unknown) {
      lastError = err as Error;
      console.warn(`[setup] Could not download from ${candidate.name}: ${(err as Error).message}`);
      console.log(`[setup] Trying next fallback...`);
    }
  }

  if (!downloaded) {
    throw new Error(`All download sources failed for Minecraft server jar. Last error: ${lastError?.message}`);
  }

  return destJar;
}

export interface SetupOptions {
  mcDir?: string;
  version?: string;
  force?: boolean;
}

/**
 * Main setup runner for local Minecraft development server.
 */
export async function setupServer(options: SetupOptions = {}): Promise<void> {
  console.log('================================================================');
  console.log('       Aldeano Build MCP - Local Minecraft Server Setup        ');
  console.log('================================================================\n');

  // 1. Check Java
  console.log('[step 1/4] Checking Java runtime environment...');
  const javaCheck = checkJavaInstalled();
  if (!javaCheck.installed) {
    console.error('\n[ERROR] Java is not installed or not found in PATH.');
    console.error('Minecraft server requires Java 17 or Java 21 to run.');
    console.error('Please install OpenJDK / Eclipse Temurin: https://adoptium.net/');
    process.exit(1);
  }

  console.log(`[setup] Java detected: ${javaCheck.version || 'Version detected'} (${javaCheck.output?.split('\n')[0]})`);
  if (javaCheck.majorVersion && javaCheck.majorVersion < 17) {
    console.warn(`[setup] WARNING: Detected Java version is ${javaCheck.majorVersion}. Minecraft 1.20+ recommends Java 17 or 21.`);
  }

  // 2. Prepare Directory
  console.log('\n[step 2/4] Verifying local development directory...');
  const mcDir = options.mcDir || getMinecraftDevDir();
  ensureMinecraftDir(mcDir);

  // 3. Download Server JAR
  console.log('\n[step 3/4] Checking Minecraft server jar...');
  const version = options.version || process.env.MC_VERSION || DEFAULT_MC_VERSION;
  const force = options.force || process.argv.includes('--force');
  await downloadServerJar(mcDir, version, force);

  // 4. Configuration (EULA + server.properties)
  console.log('\n[step 4/4] Writing configuration files...');
  writeEula(mcDir);
  writeServerProperties(mcDir);

  console.log('\n================================================================');
  console.log(' Local Minecraft server is configured and ready!');
  console.log(` Directory: ${mcDir}`);
  console.log(' Start server with: npm run mc:start');
  console.log('================================================================\n');
}

// Direct execution check
const currentFile = fileURLToPath(import.meta.url);
const invokedFile = process.argv[1] ? path.resolve(process.argv[1]) : '';

if (invokedFile === currentFile || invokedFile.endsWith('setup-server.ts') || invokedFile.endsWith('setup-server.js')) {
  setupServer().catch((err) => {
    console.error('\n[ERROR] Server setup failed:', err);
    process.exit(1);
  });
}
