import mineflayer from 'mineflayer';
import { finalizeVoxels } from '../../../src/build/verification/build-completion.js';
import {Vec3} from 'vec3';
import {existsSync,readFileSync,writeFileSync, mkdirSync} from 'node:fs';
mkdirSync(new URL('../artifacts/', import.meta.url), { recursive: true });
import {design,vox,jobs,structures,labels,W,D,MAX_Y,key} from './konoha-design.mts';
import {BuildPreflight} from '../../../src/build/verification/build-preflight.js';
import {BoundedTeleportService} from '../../../src/services/bounded-teleport-service.js';
import {ParallelFastExecutor} from '../../../src/build/executor/parallel-fast-executor.js';
import type {FastCommandOperation} from '../../../src/build/executor/fast-command-batch.js';
const file=new URL('../artifacts/konoha-progress.json', import.meta.url);
const phases=['konoha_terrain','konoha_streets','konoha_mountain','konoha_hokage_faces','konoha_walls','konoha_center','konoha_institutions','konoha_districts','konoha_training_water','konoha_forest','konoha_details'];
type State={origin:{x:number,y:number,z:number},preflight:boolean,jobs:Record<string,{status:string,commands?:number,blocks?:number}>,labelsDone:boolean,verified:number,started:string};
const state:State=existsSync(file)?JSON.parse(readFileSync(file,'utf8').replace(/^\uFEFF/,'')):{origin:{x:2100,y:-59,z:900},preflight:false,jobs:{},labelsDone:false,verified:0,started:new Date().toISOString()};
const save=()=>writeFileSync(file,JSON.stringify(state,null,2));
const bots:mineflayer.Bot[]=[];
async function connect(name:string){const bot=mineflayer.createBot({host:'127.0.0.1',port:9999,username:name});bots.push(bot);await new Promise<void>((res,rej)=>{bot.once('spawn',res);bot.once('error',rej);bot.once('kicked',r=>rej(Error(String(r))));});await bot.waitForChunksToLoad();if(bot.game.gameMode!=='creative')throw Error('Creative mode required');return bot;}
const world=(x:number,y:number,z:number)=>({x:state.origin.x+x,y:state.origin.y+y,z:state.origin.z+z});
type Cell={x:number,y:number,z:number,b:string,phase:string};
const tiles=new Map<string,Cell[]>();
function prepare(){for(const [k,b]of vox){const [x,y,z]=k.split(',').map(Number),worker=Math.floor(x/96),tx=Math.floor((x-worker*96)/48)*48+worker*96,tz=Math.floor(z/48)*48,tk=`${worker}:${tx}:${tz}`;const row=tiles.get(tk)??[];row.push({x,y,z,b,phase:jobs.get(k)??'konoha_terrain'});tiles.set(tk,row);}}
function compress(cells:Cell[]):FastCommandOperation[]{const rows=new Map<string,Cell[]>();for(const c of cells){const rk=`${c.y},${c.z}`,r=rows.get(rk)??[];r.push(c);rows.set(rk,r);}const runs:Extract<FastCommandOperation,{type:'fill'}>[]=[];for(const r of rows.values()){r.sort((a,b)=>a.x-b.x);for(let i=0;i<r.length;){let j=i;while(j+1<r.length&&r[j+1].x===r[j].x+1&&r[j+1].b===r[i].b)j++;runs.push({type:'fill',from:world(r[i].x,r[i].y,r[i].z),to:world(r[j].x,r[j].y,r[j].z),block:r[i].b});i=j+1;}}
const groups=new Map<string,typeof runs>();for(const op of runs){const k=`${op.from.x},${op.to.x},${op.from.z},${op.block}`,g=groups.get(k)??[];g.push(op);groups.set(k,g);}const merged:FastCommandOperation[]=[];for(const g of groups.values()){g.sort((a,b)=>a.from.y-b.from.y);for(let i=0;i<g.length;){let j=i;while(j+1<g.length&&g[j+1].from.y===g[j].to.y+1&&(g[j+1].to.y-g[i].from.y+1)*(g[i].to.x-g[i].from.x+1)<=32768)j++;merged.push({...g[i],to:{...g[i].to,y:g[j].to.y}});i=j+1;}}return merged;}
async function position(bot:mineflayer.Bot,tx:number,tz:number){await new BoundedTeleportService(bot).selfTo(world(Math.min(W-1,tx+23),200,Math.min(D-1,tz+23)));}
async function submit(bot:mineflayer.Bot,ops:FastCommandOperation[],tx:number,tz:number){const tp=new BoundedTeleportService(bot);for(let i=0;i<ops.length;i+=128){await tp.selfTo(world(Math.min(W-1,tx+23),200,Math.min(D-1,tz+23)));await new ParallelFastExecutor([bot]).execute(ops.slice(i,i+128),{commandsPerTick:8});}}
function traversability(){const N=W*D,seen=new Uint8Array(N*85),queue=new Int32Array(N*85);const enc=(x:number,y:number,z:number)=>(y*D+z)*W+x;
const open=(x:number,y:number,z:number)=>{const b=vox.get(key(x,y,z));return !b||b.includes('_door[')&&b.includes('open=true')||b.startsWith('ladder')||b==='flower_pot';};
const walk=(x:number,y:number,z:number)=>{if(x<0||x>=W||z<0||z>=D||y<1||y>=83)return false;const floor=vox.get(key(x,y-1,z));return !!floor&&!floor.startsWith('water')&&!floor.includes('leaves')&&open(x,y,z)&&open(x,y+1,z);};
let a=0,n=0;const start=enc(192,7,444);if(!walk(192,7,444))throw Error('Main entrance avenue is obstructed');queue[n++]=start;seen[start]=1;
while(a<n){const id=queue[a++],x=id%W,z=Math.floor(id/W)%D,y=Math.floor(id/N);for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]])for(const dy of [0,1,-1]){const X=x+dx,Y=y+dy,Z=z+dz;if(X<0||X>=W||Z<0||Z>=D||Y<1||Y>=83)continue;const k=enc(X,Y,Z);if(!seen[k]&&walk(X,Y,Z)){seen[k]=1;queue[n++]=k;}}}
const failures:string[]=[];for(const s of structures){if(!s.entrance)continue;const [x,y,z]=s.entrance as number[];if(!seen[enc(x,y,z)])failures.push(`${s.id}: entrance`);if(s.interior){const [xx,yy,zz]=s.interior as number[];if(!seen[enc(xx,yy,zz)])failures.push(`${s.id}: interior`);}}
for(const s of structures){if(!s.interior||!s.stories)continue;const [x,y,z]=s.interior as number[],step=s.id==='hokage_complex'?11:7;for(let f=1;f<Number(s.stories);f++)if(!seen[enc(x,y+f*step,z)])failures.push(`${s.id}: floor ${f+1}`);}
const primary=['hokage_complex','ninja_academy','konoha_hospital','ICHIRAKU RAMEN'];const check=primary.map(id=>({id,connected:!failures.some(x=>x.startsWith(id+':'))}));writeFileSync(new URL('../artifacts/konoha-route-audit.json', import.meta.url),JSON.stringify({reachableCells:n,failures,primary:check},null,2));if(failures.length)throw Error(`Route audit: ${failures.join(', ')}`);console.log(JSON.stringify({stage:'route_plan_passed',reachableCells:n,buildings:structures.filter(s=>s.entrance).length}));}
async function preflight(bot:mineflayer.Bot){const tp=new BoundedTeleportService(bot);let scanned=0;for(let x=0;x<W;x+=64)for(let z=0;z<D;z+=64){const X=Math.min(W-1,x+63),Z=Math.min(D-1,z+63);const bounds={from:world(x,0,z),to:world(X,MAX_Y,Z)};const p=new BuildPreflight(bot,2_000_000,45000,v=>tp.selfTo(v));const r=await p.inspectBounds(bounds,'fast');scanned+=r.scannedBlocks;console.log(JSON.stringify({stage:'preflight',scanned,total:W*D*(MAX_Y+1)}));}state.preflight=true;save();}
async function clearVillages(bot:mineflayer.Bot){let done=0;for(let tx=0;tx<W;tx+=48)for(let tz=0;tz<D;tz+=48){const id=`konoha_site_clear:${tx}:${tz}`;if(state.jobs[id]?.status==='complete'){done++;continue;}await position(bot,tx,tz);const ops:FastCommandOperation[]=[];for(let z=tz;z<Math.min(D,tz+48);z+=4)ops.push({type:'fill',from:world(tx,0,z),to:world(Math.min(W-1,tx+47),MAX_Y,Math.min(D-1,z+3)),block:'air'});await submit(bot,ops,tx,tz);await bot.waitForTicks(6);state.jobs[id]={status:'complete',commands:ops.length};save();done++;if(done%8===0||done===80)console.log(JSON.stringify({stage:'site_cleared',regions:done,total:80}));}}
async function executePhase(phase:string){await Promise.all(bots.map(async(bot,worker)=>{for(const [tk,cells]of tiles){if(Number(tk.split(':')[0])!==worker)continue;const region=cells.filter(c=>c.phase===phase);if(!region.length)continue;const id=`${phase}:${tk}`;if(state.jobs[id]?.status==='complete')continue;const [,tx,tz]=tk.split(':').map(Number);await position(bot,tx,tz);const ops=compress(region);state.jobs[id]={status:'running',blocks:region.length,commands:ops.length};save();await submit(bot,ops,tx,tz);state.jobs[id].status='complete';save();}}));console.log(JSON.stringify({stage:'phase_complete',phase,completedJobs:Object.values(state.jobs).filter(s=>s.status==='complete').length}));}
async function verify(){let total=0,repaired=0;await Promise.all(bots.map(async(bot,worker)=>{for(const [tk,cells]of tiles){if(Number(tk.split(':')[0])!==worker)continue;const [,tx,tz]=tk.split(':').map(Number);await position(bot,tx,tz);let missing:Cell[]=[];for(const c of cells){const p=world(c.x,c.y,c.z),b=bot.blockAt(new Vec3(p.x,p.y,p.z));if(!b)throw Error(`SITE_UNAVAILABLE verification ${tk}`);if(b.name!==c.b.split('[')[0])missing.push(c);}
for(let pass=0;missing.length&&pass<3;pass++){await submit(bot,compress(missing),tx,tz);repaired+=missing.length;await bot.waitForTicks(25);missing=missing.filter(c=>{const p=world(c.x,c.y,c.z);return bot.blockAt(new Vec3(p.x,p.y,p.z))?.name!==c.b.split('[')[0];});}
if(missing.length)throw Error(`Failed blocks ${tk}: ${JSON.stringify(missing.slice(0,5))}`);
// Check expected interior and street air as well as solid placements.
for(const s of structures){if(!s.interior)continue;const [x,y,z]=s.interior as number[];if(x<tx||x>tx+47||z<tz||z>tz+47)continue;for(const dy of [0,1]){const p=world(x,y+dy,z),actual=bot.blockAt(new Vec3(p.x,p.y,p.z));const intended=vox.get(key(x,y+dy,z));if(!intended&&(!actual||!['air','cave_air','void_air'].includes(actual.name)))throw Error(`Interior obstructed: ${s.id}`);}}
total+=cells.length;state.verified=total;save();console.log(JSON.stringify({stage:'verified',blocks:total,total:vox.size,region:tk}));}}));return {total,repaired};}
async function sign(){if(state.labelsDone)return;for(const bot of bots){const worker=bots.indexOf(bot);for(const l of labels.filter(v=>Math.floor(v.x/96)===worker)){await position(bot,Math.floor(l.x/48)*48,Math.floor(l.z/48)*48);const p=world(l.x,l.y,l.z),text=JSON.stringify(JSON.stringify({text:l.text,color:'black'}));bot.chat(`/summon minecraft:text_display ${p.x} ${p.y} ${p.z} {Tags:["konoha_benchmark"],billboard:"center",background:2003202047,line_width:300,text:${text},transformation:{scale:[1.5f,1.5f,1.5f]}}`);await bot.waitForTicks(2);}}state.labelsDone=true;save();}
async function run(){design();traversability();prepare();console.log(JSON.stringify({stage:'designed',blocks:vox.size,dimensions:[W,D],structures:structures.length,tiles:tiles.size,origin:state.origin}));const b=await connect('KonohaWorker1');
const invalid=[...new Set(vox.values())].filter(name=>!b.registry.blocksByName[name.split('[')[0]]);if(invalid.length)throw Error(`Unknown construction blocks: ${invalid.join(', ')}`);
if(!state.preflight){await clearVillages(b);await preflight(b);}
for(let i=2;i<=4;i++)await connect(`KonohaWorker${i}`);
writeFileSync(new URL('../artifacts/konoha-manifest.json', import.meta.url),JSON.stringify({origin:state.origin,bounds:{from:world(0,0,0),to:world(W-1,MAX_Y,D-1)},dimensions:[W,D],urbanCore:[334,310],structures,labels,regions:[0,1,2,3].map(i=>({worker:i+1,x:[i*96,i*96+95],z:[0,D-1]})),jobs:phases,verifyAfterBuild:true,visualReview:false},null,2));
for(const phase of phases)await executePhase(phase);await sign();const checked=await verify();traversability();const pending=Object.values(state.jobs).filter(s=>s.status!=='complete').length;if(W<300||D<300||checked.total!==vox.size||pending)throw Error('Benchmark completion criteria failed');
await finalizeVoxels(b,vox,state.origin,{mode:'fast'});
const result={completed:true,origin:state.origin,dimensions:{xSpan:W,zSpan:D},urbanCore:{xSpan:334,zSpan:310},requestedBlocks:vox.size,placedBlocks:checked.total,failedBlocks:0,repairedBlocks:checked.repaired,structures:structures.length,buildings:structures.filter(s=>s.entrance).length,residences:structures.filter(s=>s.kind==='residential').length,hokageFaces:5,watchtowers:10,labels:labels.length,completedJobs:Object.keys(state.jobs).length,pendingJobs:pending,workersCompleted:4,chunksCompleted:Math.ceil(W/16)*Math.ceil(D/16),routesConnected:true,interiorsAccessible:true,visualReview:false,finished:new Date().toISOString()};writeFileSync(new URL('../artifacts/konoha-result.json', import.meta.url),JSON.stringify(result,null,2));console.log(JSON.stringify({stage:'completed',...result}));}
run().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>{for(const b of bots)b.quit();setTimeout(()=>process.exit(process.exitCode??0),1000);});
