import { z } from 'zod';
import type { ToolFactory } from '../tool-factory.js';
import type { BuildService } from '../build/build-service.js';
import type { BlockPosition, BuildMode, PositionTuple } from '../build/build-types.js';
import { tupleToPosition } from '../build/build-types.js';
import { buildLine } from '../build/primitives/line.js';
import { buildWall } from '../build/primitives/wall.js';
import { buildFloor } from '../build/primitives/floor.js';
import { buildColumn } from '../build/primitives/column.js';
import { buildBox, buildHollowBox } from '../build/primitives/box.js';
import { buildCylinder } from '../build/primitives/cylinder.js';
import { buildSphere } from '../build/primitives/sphere.js';
import { buildRoof, buildRoofDetailed, type RoofOptions } from '../build/primitives/roof.js';
import { designRequirementsSchema } from '../build/verification/design-validator.js';
import { BlueprintTransformer } from '../blueprints/blueprint-transform.js';

const position = z.tuple([z.coerce.number().int(), z.coerce.number().int(), z.coerce.number().int()]);
const mode = z.enum(['physical', 'fast', 'cinematic']).optional();
const verifyAfterBuild = z.boolean().optional().describe('Whether to run post-build structural verification. Ask the user before choosing this value.');
const blueprint = z.union([z.string(), z.record(z.unknown())]);

function json(factory: ToolFactory, value: unknown) { return factory.createResponse(JSON.stringify(value)); }
function p(value: PositionTuple): BlockPosition { return tupleToPosition(value); }

export function registerBuildTools(factory: ToolFactory, service: BuildService): void {
  const transformer = new BlueprintTransformer();
  factory.registerTool('build.roof', 'Build a closed flat, gable or hip roof with thickness, overhang and oriented stairs. Preflight is mandatory.', {
    from:position,to:position,block:z.string().min(1),style:z.enum(['flat','gable','hip']).optional(),axis:z.enum(['x','z']).optional(),height:z.number().int().nonnegative().max(128).optional(),thickness:z.number().int().min(1).max(16).optional(),overhang:z.number().int().min(0).max(16).optional(),closeEnds:z.boolean().optional(),gableBlock:z.string().optional(),ridgeBlock:z.string().optional(),mode,verifyAfterBuild
  },async ({from,to,block,mode:selected,verifyAfterBuild:verify,...options}:{from:PositionTuple;to:PositionTuple;block:string;mode?:BuildMode;verifyAfterBuild?:boolean}&RoofOptions)=>json(factory,await service.executePlacements('roof',buildRoofDetailed(p(from),p(to),block,options),selected,{verifyAfterBuild:verify})));
  factory.registerTool('build.blueprint.v2', 'Execute a blueprint with an exact declared unique block count and optional architectural contracts.', {
    blueprint,origin:position,mode,verifyAfterBuild,expectedBlocks:z.number().int().nonnegative(),design:designRequirementsSchema.optional()
  },async ({blueprint:value,origin,mode:selected,verifyAfterBuild:verify,expectedBlocks,design}:{blueprint:unknown;origin:PositionTuple;mode?:BuildMode;verifyAfterBuild?:boolean;expectedBlocks:number;design?:import('../build/build-types.js').DesignRequirements})=>json(factory,await service.buildBlueprint(value,p(origin),selected,{verifyAfterBuild:verify,expectedBlocks,design})));
  factory.registerTool('build.checkpoints', 'List persisted construction IDs available for recovery.', {},async()=>json(factory,{builds:service.listCheckpoints()}));
  factory.registerTool('build.recover', 'Inspect a saved construction site, verify existing blocks and resume only pending placements. Never resume on another server or dimension.', {buildId:z.string().min(1)},async ({buildId}:{buildId:string})=>json(factory,await service.recover(buildId)));
  factory.registerTool('build-line', 'Visit and inspect an empty site, then build a deterministic 3D line. Ask whether post-build validation is wanted.', { from: position, to: position, block: z.string().min(1), mode, verifyAfterBuild }, async ({ from, to, block, mode: selected, verifyAfterBuild: verify }: { from: PositionTuple; to: PositionTuple; block: string; mode?: BuildMode; verifyAfterBuild?: boolean }) => json(factory, await service.executePlacements('line', buildLine(p(from), p(to), block), selected, { verifyAfterBuild: verify })));
  factory.registerTool('build-wall', 'Visit and inspect an empty site, then build a wall. Ask whether post-build validation is wanted.', { from: position, to: position, height: z.coerce.number().int().positive(), block: z.string().min(1), mode, verifyAfterBuild }, async ({ from, to, height, block, mode: selected, verifyAfterBuild: verify }: { from: PositionTuple; to: PositionTuple; height: number; block: string; mode?: BuildMode; verifyAfterBuild?: boolean }) => json(factory, await service.executePlacements('wall', buildWall(p(from), p(to), height, block), selected, { verifyAfterBuild: verify })));
  factory.registerTool('build-floor', 'Visit and inspect an empty site, then build a floor. Ask whether post-build validation is wanted.', { from: position, to: position, block: z.string().min(1), mode, verifyAfterBuild }, async ({ from, to, block, mode: selected, verifyAfterBuild: verify }: { from: PositionTuple; to: PositionTuple; block: string; mode?: BuildMode; verifyAfterBuild?: boolean }) => json(factory, await service.executePlacements('floor', buildFloor(p(from), p(to), block), selected, { verifyAfterBuild: verify })));
  factory.registerTool('build-column', 'Visit and inspect an empty site, then build a column. Ask whether post-build validation is wanted.', { origin: position, height: z.coerce.number().int().positive(), block: z.string().min(1), mode, verifyAfterBuild }, async ({ origin, height, block, mode: selected, verifyAfterBuild: verify }: { origin: PositionTuple; height: number; block: string; mode?: BuildMode; verifyAfterBuild?: boolean }) => json(factory, await service.executePlacements('column', buildColumn(p(origin), height, block), selected, { verifyAfterBuild: verify })));
  factory.registerTool('build-box', 'Visit and inspect an empty site, then build a filled cuboid. Ask whether post-build validation is wanted.', { from: position, to: position, block: z.string().min(1), mode, verifyAfterBuild }, async ({ from, to, block, mode: selected, verifyAfterBuild: verify }: { from: PositionTuple; to: PositionTuple; block: string; mode?: BuildMode; verifyAfterBuild?: boolean }) => json(factory, await service.executePlacements('box', buildBox(p(from), p(to), block), selected, { verifyAfterBuild: verify })));
  factory.registerTool('build-hollow-box', 'Visit and inspect an empty site, then build a cuboid shell. Ask whether post-build validation is wanted.', { from: position, to: position, block: z.string().min(1), mode, verifyAfterBuild }, async ({ from, to, block, mode: selected, verifyAfterBuild: verify }: { from: PositionTuple; to: PositionTuple; block: string; mode?: BuildMode; verifyAfterBuild?: boolean }) => json(factory, await service.executePlacements('hollow-box', buildHollowBox(p(from), p(to), block), selected, { verifyAfterBuild: verify })));
  factory.registerTool('build-cylinder', 'Visit and inspect an empty site, then build a cylinder. Ask whether post-build validation is wanted.', { center: position, radius: z.coerce.number().int().nonnegative(), height: z.coerce.number().int().positive(), block: z.string().min(1), hollow: z.boolean().optional(), mode, verifyAfterBuild }, async ({ center, radius, height, block, hollow = false, mode: selected, verifyAfterBuild: verify }: { center: PositionTuple; radius: number; height: number; block: string; hollow?: boolean; mode?: BuildMode; verifyAfterBuild?: boolean }) => json(factory, await service.executePlacements('cylinder', buildCylinder(p(center), radius, height, block, hollow), selected, { verifyAfterBuild: verify })));
  factory.registerTool('build-sphere', 'Visit and inspect an empty site, then build a sphere. Ask whether post-build validation is wanted.', { center: position, radius: z.coerce.number().int().nonnegative(), block: z.string().min(1), hollow: z.boolean().optional(), mode, verifyAfterBuild }, async ({ center, radius, block, hollow = false, mode: selected, verifyAfterBuild: verify }: { center: PositionTuple; radius: number; block: string; hollow?: boolean; mode?: BuildMode; verifyAfterBuild?: boolean }) => json(factory, await service.executePlacements('sphere', buildSphere(p(center), radius, block, hollow), selected, { verifyAfterBuild: verify })));
  factory.registerTool('build-roof', 'Visit and inspect an empty site, then build a roof. Ask whether post-build validation is wanted.', { from: position, to: position, block: z.string().min(1), axis: z.enum(['x', 'z']).optional(), mode, verifyAfterBuild }, async ({ from, to, block, axis = 'x', mode: selected, verifyAfterBuild: verify }: { from: PositionTuple; to: PositionTuple; block: string; axis?: 'x' | 'z'; mode?: BuildMode; verifyAfterBuild?: boolean }) => json(factory, await service.executePlacements('roof', buildRoof(p(from), p(to), block, axis), selected, { verifyAfterBuild: verify })));

  factory.registerTool('fill-region', 'Fill a bounded region with one block. Risk: high; destructive when overwriting.', { from: position, to: position, block: z.string().min(1), mode }, async ({ from, to, block, mode: selected }: { from: PositionTuple; to: PositionTuple; block: string; mode?: BuildMode }) => json(factory, await service.fillRegion({ from: p(from), to: p(to) }, block, selected)));
  factory.registerTool('clear-region', 'Clear a bounded region. Risk: high; destructive.', { from: position, to: position, mode }, async ({ from, to, mode: selected }: { from: PositionTuple; to: PositionTuple; mode?: BuildMode }) => json(factory, await service.clearRegion({ from: p(from), to: p(to) }, selected)));
  factory.registerTool('replace-blocks', 'Replace matching blocks in a bounded region. Risk: high; destructive.', { from: position, to: position, fromBlock: z.string().min(1), toBlock: z.string().min(1), mode }, async ({ from, to, fromBlock, toBlock, mode: selected }: { from: PositionTuple; to: PositionTuple; fromBlock: string; toBlock: string; mode?: BuildMode }) => json(factory, await service.replaceBlocks({ from: p(from), to: p(to) }, fromBlock, toBlock, selected)));
  factory.registerTool('clone-region', 'Clone a bounded source region to a destination origin. Risk: medium.', { from: position, to: position, destination: position, mode }, async ({ from, to, destination, mode: selected }: { from: PositionTuple; to: PositionTuple; destination: PositionTuple; mode?: BuildMode }) => json(factory, await service.cloneRegion({ from: p(from), to: p(to) }, p(destination), selected)));

  factory.registerTool('build.preview', 'Validate and preview a blueprint without changing Minecraft.', { blueprint, origin: position.optional(), mode }, async ({ blueprint: value, origin = [0, 0, 0], mode: selected }: { blueprint: unknown; origin?: PositionTuple; mode?: BuildMode }) => json(factory, service.preview(value, p(origin), selected)));
  factory.registerTool('blueprint.validate', 'Validate blueprint schema, limits, block names, coordinates, duplicates and dependencies.', { blueprint }, async ({ blueprint: value }: { blueprint: unknown }) => {
    const parsed = service.parseBlueprint(value); return json(factory, service.validateBlueprint(parsed));
  });
  factory.registerTool('blueprint.transform', 'Apply deterministic translation, rotation, or mirroring and return a new blueprint.', {
    blueprint,
    transforms: z.array(z.object({ operation: z.enum(['translate', 'rotate90', 'rotate180', 'rotate270', 'mirrorX', 'mirrorZ']), x: z.coerce.number().int().optional(), y: z.coerce.number().int().optional(), z: z.coerce.number().int().optional() })).min(1)
  }, async ({ blueprint: value, transforms }: { blueprint: unknown; transforms: Array<{ operation: 'translate' | 'rotate90' | 'rotate180' | 'rotate270' | 'mirrorX' | 'mirrorZ'; x?: number; y?: number; z?: number }> }) => {
    let result = service.parseBlueprint(value);
    for (const transform of transforms) {
      result = transform.operation === 'translate' ? transformer.translate(result, transform.x ?? 0, transform.y ?? 0, transform.z ?? 0) : transformer[transform.operation](result);
    }
    return json(factory, result);
  });
  factory.registerTool('build.blueprint', 'Visit and inspect an empty site, then execute a planned blueprint. Ask the user whether post-build validation is wanted.', { blueprint, origin: position, mode, verifyAfterBuild }, async ({ blueprint: value, origin, mode: selected, verifyAfterBuild: verify }: { blueprint: unknown; origin: PositionTuple; mode?: BuildMode; verifyAfterBuild?: boolean }) => json(factory, await service.buildBlueprint(value, p(origin), selected, { verifyAfterBuild: verify })));
  factory.registerTool('check-build', 'Get structured progress for a build ID.', { buildId: z.string().min(1) }, async ({ buildId }: { buildId: string }) => json(factory, service.getProgress(buildId) ?? { success: false, error: { code: 'BUILD_NOT_FOUND', message: `Unknown build '${buildId}'` } }));
  factory.registerTool('verify-build', 'Visit sectors and compare a completed build plan with the current world.', { buildId: z.string().min(1), includeExtras: z.boolean().optional() }, async ({ buildId, includeExtras = false }: { buildId: string; includeExtras?: boolean }) => json(factory, await service.verifyAsync(buildId, includeExtras)));
  factory.registerTool('repair-build', 'Repair only differences found during verification, with bounded passes.', { buildId: z.string().min(1) }, async ({ buildId }: { buildId: string }) => json(factory, await service.repair(buildId)));
  factory.registerTool('build.cancel', 'Cancel an active build without disconnecting Minecraft.', { buildId: z.string().min(1) }, async ({ buildId }: { buildId: string }) => json(factory, { success: service.cancel(buildId), buildId }));
  factory.registerTool('build.pause', 'Pause an active build in memory.', { buildId: z.string().min(1) }, async ({ buildId }: { buildId: string }) => json(factory, { success: service.pause(buildId), buildId }));
  factory.registerTool('build.resume', 'Resume a paused build.', { buildId: z.string().min(1) }, async ({ buildId }: { buildId: string }) => json(factory, { success: service.resume(buildId), buildId }));
  factory.registerTool('build.history', 'List recent build metadata and metrics.', { limit: z.coerce.number().int().positive().max(200).optional() }, async ({ limit = 50 }: { limit?: number }) => json(factory, { builds: service.history.list(limit) }));
}
